# Generated by Django 3.2.5 on 2021-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shortenerurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenerurl',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
