# Generated by Django 3.2.5 on 2021-07-11 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_shortenerurl_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenerurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortenerurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
