# Generated by Django 3.2.5 on 2021-07-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20210711_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenerurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortenerurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
